<div class="page-content">
    <div class="container-fluid">
        <!-- start page title -->
        <div class="row">
            <div class="col-12">
                <div class="page-title-box d-flex align-items-center justify-content-between">
                    <h4 class="mb-0 font-size-18">Usuarios Administradores</h4>

                    <div class="page-title-right">
                        <ol class="breadcrumb m-0">
                            <li class="breadcrumb-item active">
                                <button type="button" class="btn btn-success waves-effect waves-light extend-new-recurso" data-toggle="modal" data-target=".nuevo"> Nuevo</button>
                            </li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>
        <!-- end page title -->
        <div class="row contenido-tb">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <table id="recursos-table" class="table table-striped table-bordered dt-responsive nowrap" style="border-collapse: collapse; border-spacing: 0; width: 100%;">
                            <thead>
                                <tr>
                                    <th>Nombre</th>
                                    <th>Correo</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                            </tbody>
                        </table>

                    </div>
                </div>
            </div>
        </div>
        <!-- end row -->
    </div> <!-- container-fluid -->
</div>
<!-- End Page-content -->


<!-- modal secccion-->
<div class="modal fade nuevo" tabindex="-1" role="dialog" aria-labelledby="myExtraLargeModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title mt-0">Nuevo</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form method="post" id="frm_nuevo" class="custom-validation">
                <div class="modal-body">
                    <div class="row">


                        <div class="col-md-12">
                            <div class="form-group">
                                <input name="x1" id="x1" class="form-control" type="text" placeholder="Nombre" required="">
                            </div>
                        </div>

                        <div class="col-md-6">
                            <div class="form-group">
                                <input name="x2" id="x2" class="form-control" type="email" placeholder="Correo electrónico" required="">
                            </div>
                        </div>

                        <div class="col-md-6">
                            <div class="form-group">
                                <input data-parsley-minlength="6" id="x3" name="x3" class="form-control" type="password" placeholder="Contraseña" required="" autocomplete="new-password">
                            </div>
                        </div>




                    </div>
                </div>
                <div class="modal-footer">
                    <div class="spinner-border text-success" role="status" style="display: none">
                        <span class="sr-only">Loading...</span>
                    </div>
                    <button type="button" class="btn btn-secondary waves-effect" data-dismiss="modal">Cerrar</button>
                    <button type="submit" class="btn btn-success waves-effect waves-light" id="nuevo_ajax">Guardar</button>
                </div>
            </form>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->


<!-- edit modal-->
<div class="modal fade" id="editar-recurso" tabindex="-1" role="dialog" aria-labelledby="myExtraLargeModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title mt-0">Editar</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form role="form" method="post" id="frm_editar" class="custom-validation">
                <div class="modal-body">
                    <div class="row">


                        <div class="col-md-12">
                            <div class="form-group">
                                <label class="control-label">Nombre:</label>
                                <input name="x1_x" id="x1_x" class="form-control" type="text" placeholder="Nombre" required="">
                            </div>
                        </div>



                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="control-label">Correo electrónico:</label>
                                <input name="x2_x" id="x2_x" class="form-control" type="email" placeholder="Correo electrónico" required="">
                            </div>
                        </div>

                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="control-label">*Opcional Cambiar</label>
                                <input id="x3_x" name="x3_x" data-parsley-minlength="6" class="form-control" type="password" placeholder="Contraseña" autocomplete="new-password">
                            </div>
                        </div>


                    </div>
                </div>
                <div class="modal-footer">
                    <div class="spinner-border text-success" role="status" style="display: none">
                        <span class="sr-only">Loading...</span>
                    </div>
                    <button type="button" class="btn btn-secondary waves-effect" data-dismiss="modal">Cerrar</button>
                    <button type="submit" class="btn btn-success waves-effect waves-light" id="editar_ajax">Guardar</button>
                </div>
            </form>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->